# Generated by Django 3.2.8 on 2021-10-17 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Trees',
            fields=[
                ('TreeId', models.AutoField(primary_key=True, serialize=False)),
                ('TreeName', models.CharField(max_length=50)),
                ('TreePrice', models.IntegerField()),
                ('TreeQuantity', models.IntegerField()),
                ('TreeContent', models.TextField()),
                ('TreeImage', models.CharField(max_length=350)),
                ('TreeCreateAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('TreeUpdateAt', models.DateTimeField(blank=True)),
            ],
        ),
    ]
